/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutPromptManagementIndexImport } from './routes/_layout/prompt-management/index'
import { Route as LayoutAudioUploadIndexImport } from './routes/_layout/audio-upload/index'
import { Route as LayoutAudioRecordingsIndexImport } from './routes/_layout/audio-recordings/index'
import { Route as LayoutAudioRecordingsIdImport } from './routes/_layout/audio-recordings/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutPromptManagementIndexRoute =
  LayoutPromptManagementIndexImport.update({
    id: '/prompt-management/',
    path: '/prompt-management/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAudioUploadIndexRoute = LayoutAudioUploadIndexImport.update({
  id: '/audio-upload/',
  path: '/audio-upload/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAudioRecordingsIndexRoute = LayoutAudioRecordingsIndexImport.update(
  {
    id: '/audio-recordings/',
    path: '/audio-recordings/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutAudioRecordingsIdRoute = LayoutAudioRecordingsIdImport.update({
  id: '/audio-recordings/$id',
  path: '/audio-recordings/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/audio-recordings/$id': {
      id: '/_layout/audio-recordings/$id'
      path: '/audio-recordings/$id'
      fullPath: '/audio-recordings/$id'
      preLoaderRoute: typeof LayoutAudioRecordingsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/audio-recordings/': {
      id: '/_layout/audio-recordings/'
      path: '/audio-recordings'
      fullPath: '/audio-recordings'
      preLoaderRoute: typeof LayoutAudioRecordingsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/audio-upload/': {
      id: '/_layout/audio-upload/'
      path: '/audio-upload'
      fullPath: '/audio-upload'
      preLoaderRoute: typeof LayoutAudioUploadIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/prompt-management/': {
      id: '/_layout/prompt-management/'
      path: '/prompt-management'
      fullPath: '/prompt-management'
      preLoaderRoute: typeof LayoutPromptManagementIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAudioRecordingsIdRoute: typeof LayoutAudioRecordingsIdRoute
  LayoutAudioRecordingsIndexRoute: typeof LayoutAudioRecordingsIndexRoute
  LayoutAudioUploadIndexRoute: typeof LayoutAudioUploadIndexRoute
  LayoutPromptManagementIndexRoute: typeof LayoutPromptManagementIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAudioRecordingsIdRoute: LayoutAudioRecordingsIdRoute,
  LayoutAudioRecordingsIndexRoute: LayoutAudioRecordingsIndexRoute,
  LayoutAudioUploadIndexRoute: LayoutAudioUploadIndexRoute,
  LayoutPromptManagementIndexRoute: LayoutPromptManagementIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/audio-recordings': typeof LayoutAudioRecordingsIndexRoute
  '/audio-upload': typeof LayoutAudioUploadIndexRoute
  '/prompt-management': typeof LayoutPromptManagementIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/audio-recordings': typeof LayoutAudioRecordingsIndexRoute
  '/audio-upload': typeof LayoutAudioUploadIndexRoute
  '/prompt-management': typeof LayoutPromptManagementIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/_layout/audio-recordings/': typeof LayoutAudioRecordingsIndexRoute
  '/_layout/audio-upload/': typeof LayoutAudioUploadIndexRoute
  '/_layout/prompt-management/': typeof LayoutPromptManagementIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/audio-recordings/$id'
    | '/audio-recordings'
    | '/audio-upload'
    | '/prompt-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/audio-recordings/$id'
    | '/audio-recordings'
    | '/audio-upload'
    | '/prompt-management'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/audio-recordings/$id'
    | '/_layout/audio-recordings/'
    | '/_layout/audio-upload/'
    | '/_layout/prompt-management/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/audio-recordings/$id",
        "/_layout/audio-recordings/",
        "/_layout/audio-upload/",
        "/_layout/prompt-management/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/audio-recordings/$id": {
      "filePath": "_layout/audio-recordings/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/audio-recordings/": {
      "filePath": "_layout/audio-recordings/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/audio-upload/": {
      "filePath": "_layout/audio-upload/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/prompt-management/": {
      "filePath": "_layout/prompt-management/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
